version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"